export const VimmRASystemMap = {
	"Atari 2600": 0,
	"Atari 5200": 0,
	Nintendo: 0,
	"Master System": 0,
	"Atari 7800": 0,
	"TurboGrafx-16": 0,
	Genesis: 1,
	"TurboGrafx-CD": 0,
	"Super Nintendo": 0,
	"CD-i": 0,
	"Sega CD": 0,
	Jaguar: 0,
	"Sega 32X": 0,
	Saturn: 0,
	PlayStation: 0,
	"Jaguar CD": 0,
	"Nintendo 64": 0,
	Dreamcast: 0,
	"PlayStation 2": 0,
	GameCube: 0,
	Xbox: 0,
	"Xbox 360": 0,
	"Xbox 360 (Digital)": 0,
	"PlayStation 3": 0,
	Wii: 0,
	WiiWare: 0,
	"Game Boy": 0,
	Lynx: 0,
	"Game Gear": 0,
	"Virtual Boy": 0,
	"Game Boy Color": 0,
	"Game Boy Advance": 0,
	"Nintendo DS": 0,
	"PlayStation Portable": 0,
	"Nintendo 3DS": 0,
} satisfies Record<string, number>;
